name: Check Code Quality
on: [push, pull_request]
env:
  PUBLIC_APIURL: ${{ vars.PUBLIC_APIURL }}
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Run Prettier Check
        if: ${{ !cancelled() }}
        run: pnpm run lint:prettier-only
      - name: Run ESLint
        if: ${{ !cancelled() }}
        run: pnpm run lint:eslint-only
      - name: Run Svelte checker
        if: ${{ !cancelled() }}
        run: pnpm run check
